@WebApi_HostAddress = http://localhost:5175

#Pobieranie wszystkich
GET {{WebApi_HostAddress}}/api/contacts?Page=1&PageSize=10
Accept: application/json

### Pobieranie po Id konkretnego 
GET {{WebApi_HostAddress}}/api/contacts/6e03f048-205a-4184-8e81-46035d604d35
Accept: application/json

### Tworzenie nowego kontaktu 
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Piotr",
  "lastName" : "Żaba",
  "Email": "adam@wsei.edu.pl",
  "phone": "+48123456789"
}

### Tworzenie z błędem (brak numeru telefonu oraz email) 
POST {{WebApi_HostAddress}}/api/contacts/
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName" : "Nowak"
}

### Update rekordu o podanym Id 
PUT {{WebApi_HostAddress}}/api/contacts/395c00c5-cb41-4ef9-84ce-37d02c4a2874
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "sowa",
  "position": null,
  "birthDate": null,
  "gender": 0,
  "employerId": null,
  "organizationId": null,
  "email": "adam@wsei.edu.pl",
  "phone": "+48123456789",
  "address": null
}

### Dodawanie notatki do osoby o wskazanym id
POST {{WebApi_HostAddress}}/api/contacts/4da66355-1bb3-48e2-93e6-dffc87a9c2ea/notes
Content-Type: application/json

{
  "content": "Note"
}
### Wypisanie notatek osoby o wskazanym id 
GET {{WebApi_HostAddress}}/api/contacts/4da66355-1bb3-48e2-93e6-dffc87a9c2ea/notes
Content-Type: application/json

### Usuwanie notatki o wskazanym id przypisanej do osoby o wskzanym id
DELETE {{WebApi_HostAddress}}/api/contacts/4da66355-1bb3-48e2-93e6-dffc87a9c2ea/notes/636b95de-7023-4e1c-bf3b-d4cb11575a23

### Logowanie 
POST {{WebApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
   "email": "jan.kowalski@crm.pl",
    "password": "Manager@123!"
}

###Pobranie z tokenem z logowanie (200) 
GET {{WebApi_HostAddress}}/api/contacts
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjkzQTdGRkRELTA1N0YtNDAyMS05QzY4LUZFMDY5NTFGRkE2NSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Imphbi5rb3dhbHNraUBjcm0ucGwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJKYW4iLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zdXJuYW1lIjoiS293YWxza2kiLCJkZXBhcnRtZW50IjoiU2FsZXMiLCJqdGkiOiI3ZTVmOWViYS00NTVlLTQyYzAtYWZlOS0yOTAzYzI5MDYzNzQiLCJpYXQiOiIxNzc2NTEzNTM1IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiU2FsZXNNYW5hZ2VyIiwibmJmIjoxNzc2NTEzNTM1LCJleHAiOjE3NzY1MTcxMzUsImlzcyI6IklkZWlzQ3JtQXBpIiwiYXVkIjoiQ3JtQ2xpZW50In0.nvr-i8ArUjHh6BnZsfL1Duj91uxrBnAn9EBW0dBZ0Bc

###Pobieranie wszystkich bez tokena (401)
GET {{WebApi_HostAddress}}/api/contacts?Page=1&PageSize=10
Accept: application/json