@WebApi_HostAddress = http://localhost:5175

#Pobieranie wszystkich
GET {{WebApi_HostAddress}}/api/contacts
Accept: application/json

### Pobieranie po Id konkretnego 
GET {{WebApi_HostAddress}}/api/contacts/6e03f048-205a-4184-8e81-46035d604d35
Accept: application/json

### Tworzenie nowego kontaktu 
POST {{WebApi_HostAddress}}/api/contacts
Content-Type: application/json

{
  "firstName": "Piotr",
  "lastName" : "Żaba",
  "Email": "adam@wsei.edu.pl",
  "phone": "+48123456789"
}

### Tworzenie z błędem (brak numeru telefonu oraz email) 
POST {{WebApi_HostAddress}}/api/contacts/
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName" : "Nowak"
}

### Update rekordu o podanym Id 
PUT {{WebApi_HostAddress}}/api/contacts/395c00c5-cb41-4ef9-84ce-37d02c4a2874
Content-Type: application/json

{
  "firstName": "Adam",
  "lastName": "sowa",
  "position": null,
  "birthDate": null,
  "gender": 0,
  "employerId": null,
  "organizationId": null,
  "email": "adam@wsei.edu.pl",
  "phone": "+48123456789",
  "address": null
}

### Dodawanie notatki do osoby o wskazanym id
POST {{WebApi_HostAddress}}/api/contacts/f37b550c-2258-4eff-a594-971f36adadff/notes
Content-Type: application/json
{
  "content": "Note"
}
### Wypisanie notatek osoby o wskazanym id 
GET {{WebApi_HostAddress}}/api/contacts/4fbfdc9f-8bb3-4c25-9814-455fcb9778db/notes
Content-Type: application/json

### Usuwanie notatki o wskazanym id przypisanej do osoby o wskzanym id
DELETE {{WebApi_HostAddress}}/api/contacts/4fbfdc9f-8bb3-4c25-9814-455fcb9778db/notes/1d7cc95f-374f-4209-8058-1721b40615be
